### ISSUE TITLE
Creacion e implematacion de template para issues

### ISSUE THREAD

**Issue by Shadowrunner11** [Shadowrunner11/utils-cli#2]
- [ ] Feature
- [ ] Bug
- [ ] Sub issue
- [ ] Doc
- [ ] Creacion del modulo con N-API que interviene con el CLI
- [ ] Implementacion de Feature template
- [ ] Implementacion de Bug templates
- [ ] Implementacion de Sub issue template
- [ ] Implementacion de doc template
